version: 2
jobs:
  build:
    environment:
      DOCKER_ORG: scholzj
      DOCKER_IMAGE: base-image-security-test
      DOCKER_REGISTRY: quay.io
    docker:
      - image: scholzj/circleci-centos-java:latest
    steps:
      - setup_remote_docker
      - checkout
      - deploy:
          name: Login to Docker
          command: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY
      - run:
          name: Build project
          command: TIME_INDEX=$(date +"%Y-%m-%d-%H-%M-%S") make all
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
            context: quay-io-scholzj
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build:
            context: quay-io-scholzj